### ISSUE TITLE
"Token \"properties\" does not exist.

### ISSUE THREAD

**Issue by bbbouvier** [Theneo-Inc/theneo-tools#48]
Hello, I am recently getting the following error :

`"Token \"properties\" does not exist."`

when trying to publish documentation with github actions or even with the following command line : 

`npx theneo project import --project horizon --workspace {{my_workspace_id}} --file dist/docs/api.yaml --import-type overwrite  --publish true`

Do you have any idea what's happening?

Thanks for your help!

**Comment by robakid** [comment]
Hey @bbbouvier appologies we missed the notification, we will review it and will follow up cc @mariamnari

**Comment by bbbouvier** [comment]
Thank you for your quick response! 

I tried it, unfortunately it doesn't fix it.

Please note, that I also get the same error when run from the github actions (copy/pasted from your documentation)

```
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install
        
      - name: Generate Documentation
        run: npm run doc:generate

      - name: Update Documentation on Theneo
        uses: Theneo-Inc/api-documentation@1.8.0
        with:
          FILE_PATH: dist/docs/api.yaml
          PROJECT_SLUG: <my_project_slug>
          VERSION_SLUG: v1
          WORKSPACE_SLUG: <my_workspace_slug>
          SECRET: ${{ secrets.THENEO_API_KEY }}
          AUTO_PUBLISH: true
          IMPORT_OPTION: overwrite
          INCLUDE_GITHUB_METADATA: true
```

Which also results in : 

![Image](https://github.com/user-attachments/assets/69de578f-35ff-4137-8018-a64058d3349a)
